framework:
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en
        paths:
            - '%kernel.project_dir%/src'
        default_locale: fr
#        providers:
#            crowdin:
#                dsn: '%env(CROWDIN_DSN)%'
#            loco:
#                dsn: '%env(LOCO_DSN)%'
#            lokalise:
#                dsn: '%env(LOKALISE_DSN)%'
